= OCaml函数式编程
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectnums:

== 简介

=== 编程语言

A great general-purpose programming language...

一个伟大的通用编程语言：

* 让我们写的代码很简洁，容易理解，并位于正确的抽象层级
* 让我们为语言扩展新特性时，可以很好的融入语言的其他特性中
* 容易写出正确的代码，且性能很好
* 容易重构代码
* 容易重用代码
* 容易学习

可能有数千种通用语言。但是没有普遍优秀的编程语言。

通用语言来来去去。在您的生活中，您可能会学到一些东西。今天，它是 Java 和 C++。昨天是 Pascal 和 C。在此之前，是 Fortran 和 Lisp。谁知道明天会怎样？您可能会为特定项目使用数十种专用语言。在这个快速变化的领域，您需要能够快速适应。

*一个好的程序员必须学习如何学习新语言。*

我们使用无数种不同的编程语言来与机器和彼此进行通信：

* 通用编程语言和脚本语言: Fortran, Lisp, Basic, C, Pascal, Scheme, C++, Java, C#, Visual Basic, Perl, Python, Ruby, PHP, Javascript, Clojure, Scala, Erlang, Swift, ...
* 工具类语言: awk, sed, tcl, sh, csh, bash, ...
* 搜索类语言: regular expressions, browser queries, SQL, ...
* 展示和渲染类语言: PostScript, PDF, HTML, XML, ...
* 硬件编程语言: CCS, VHDL, Verilog, ...
* 定理证明和数学语言: Mathematica, Maple, Matlab, R, NuPRL, Isabelle/HOL, ACL2, Coq

了解超越任何特定语言细节的编程背后的原则至关重要。没有比从完全不同的角度处理编程更好的方法来了解这些原则。

=== OCaml

我们通过学习 OCaml 开始这门课程正是出于这个原因：它与你们大多数人在以前的编程课程中看到的观点截然不同。由于您已经学习了 1110 和 2110，您已经学会了如何编程。本课程让您有机会从头开始学习一门新语言，并在此过程中反思编程与语言编程之间的区别。

>“一种不会影响你对编程的思考方式的语言是不值得了解的。”————Alan J. Perlis (1922-1990)，图灵奖首位获得者

*OCaml将改变您对编程的看法。*

OCaml 是一种函数式编程语言。函数式语言的关键语言抽象是数学函数。函数将输入映射到输出；对于相同的输入，它总是产生相同的输出。也就是说，数学函数是无状态的：它们不维护任何在函数使用之间持续存在的额外信息或状态。函数是一等公民：您可以将它们用作其他函数的输入，并生成函数作为输出。用函数来表达一切可以实现一个统一而简单的编程模型，它比其他语言家族中的过程和方法更容易推理。

OCaml 支持许多高级功能，其中一些您以前会遇到过，而其中一些可能是新的：


* 代数数据类型：您可以轻松地在 OCaml 中构建复杂的数据结构，而无需担心指针和内存管理。模式匹配使它们更加方便。
* 类型推断：您不必到处写下类型信息。编译器会自动计算出大多数类型。这可以使代码更易于阅读和维护。
* 参数多态：函数和数据结构可以在类型上参数化。这对于能够重用代码至关重要。
* 垃圾收集：自动内存管理使您免于内存分配和释放的负担，这是 C 等语言中错误的常见来源。
* 模块：OCaml 通过使用模块可以轻松构建大型系统。模块（称为结构）用于封装接口（称为签名）背后的实现。通过提供操作模块的函数（称为函子），OCaml 远远超出了大多数带有模块的语言的功能。