= OCaml函数式编程
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectnums:
:stem: latexmath

== 简介

=== 编程语言

一个伟大的通用编程语言：

* 让我们写的代码很简洁，容易理解，并位于正确的抽象层级
* 让我们为语言扩展新特性时，可以很好的融入语言的其他特性中
* 容易写出正确的代码，且性能很好
* 容易重构代码
* 容易重用代码
* 容易学习

可能有数千种通用语言。但是没有普遍优秀的编程语言。

通用语言来来去去。在您的生活中，您可能会学到一些东西。今天，它是 Java 和 C++。昨天是 Pascal 和 C。在此之前，是 Fortran 和 Lisp。谁知道明天会怎样？您可能会为特定项目使用数十种专用语言。在这个快速变化的领域，您需要能够快速适应。

*一个好的程序员必须学习如何学习新语言。*

我们使用无数种不同的编程语言来与机器和彼此进行通信：

* 通用编程语言和脚本语言: Fortran, Lisp, Basic, C, Pascal, Scheme, C++, Java, C#, Visual Basic, Perl, Python, Ruby, PHP, Javascript, Clojure, Scala, Erlang, Swift, ...
* 工具类语言: awk, sed, tcl, sh, csh, bash, ...
* 搜索类语言: regular expressions, browser queries, SQL, ...
* 展示和渲染类语言: PostScript, PDF, HTML, XML, ...
* 硬件编程语言: CCS, VHDL, Verilog, ...
* 定理证明和数学语言: Mathematica, Maple, Matlab, R, NuPRL, Isabelle/HOL, ACL2, Coq

了解超越任何特定语言细节的编程背后的原则至关重要。没有比从完全不同的角度处理编程更好的方法来了解这些原则。

=== OCaml

我们通过学习 OCaml 开始这门课程正是出于这个原因：它与你们大多数人在以前的编程课程中看到的观点截然不同。由于您已经学习了 1110 和 2110，您已经学会了如何编程。本课程让您有机会从头开始学习一门新语言，并在此过程中反思编程与语言编程之间的区别。

NOTE: “一种不会影响你对编程的思考方式的语言是不值得了解的。” —— Alan J. Perlis (1922-1990)，图灵奖首位获得者

*OCaml将改变您对编程的看法。*

OCaml 是一种函数式编程语言。函数式语言的关键语言抽象是数学函数。函数将输入映射到输出；对于相同的输入，它总是产生相同的输出。也就是说，数学函数是无状态的：它们不维护任何在函数使用之间持续存在的额外信息或状态。函数是一等公民：您可以将它们用作其他函数的输入，并生成函数作为输出。用函数来表达一切可以实现一个统一而简单的编程模型，它比其他语言家族中的过程和方法更容易推理。

OCaml 支持许多高级功能，其中一些您以前会遇到过，而其中一些可能是新的：


* 代数数据类型：您可以轻松地在 OCaml 中构建复杂的数据结构，而无需担心指针和内存管理。模式匹配使它们更加方便。
* 类型推断：您不必到处写下类型信息。编译器会自动计算出大多数类型。这可以使代码更易于阅读和维护。
* 参数多态：函数和数据结构可以在类型上参数化。这对于能够重用代码至关重要。
* 垃圾收集：自动内存管理使您免于内存分配和释放的负担，这是 C 等语言中错误的常见来源。
* 模块：OCaml 通过使用模块可以轻松构建大型系统。模块（称为结构）用于封装接口（称为签名）背后的实现。通过提供操作模块的函数（称为函子），OCaml 远远超出了大多数带有模块的语言的功能。

OCaml 是一种静态类型和类型安全的编程语言。静态类型语言在编译时检测类型错误，因此无法执行带有类型错误的程序。类型安全语言限制了可以对哪些类型的数据执行哪些类型的操作。在实践中，这可以防止许多愚蠢的错误（例如，将整数视为函数）并防止许多安全问题：计算机紧急响应小组（CERT，美国政府机构，负责网络安全）报告的入侵事件中超过一半是由于缓冲区溢出，这在类型安全的语言中是不可能的。

一些语言，如 Scheme 和 Lisp，是类型安全的，但是是动态类型的。也就是说，类型错误仅在运行时被捕获。其他语言，如 C 和 C++，是静态类型的，但不是类型安全的。不能保证不会发生类型错误。

从谱系上讲，OCaml 来自其祖父是 Lisp 的编程语言系列，其中包括 Clojure、F#、Haskell 和 Racket 等现代语言。函数式语言有一种令人惊讶的趋势来预测更多主流语言的未来。 Java 于 1995 年将垃圾收集带入主流； Lisp 在 1958 年就有了它。Java 直到 2004 年的第 5 版才有泛型； ML 系列在 1990 年就有了它。在过去的 10 年里，一流的函数和类型推断已经被纳入主流语言，如 Java、C# 和 C++，在函数式语言引入它们很久之后。通过学习函数式编程，您可以了解接下来可能会发生什么。谁知道它可能是什么？ （我打赌是模式匹配。）

==== OCaml的历史

70 年代末和 80 年代初，苏格兰爱丁堡计算机科学实验室的 Robin Milner 和其他人正在研究定理证明器。传统上，定理证明器是用 Lisp 等语言实现的。米尔纳不断遇到这样一个问题，即定理证明器有时会将不正确的“证明”（即错误证明）放在一起并声称它们是有效的。所以他试图开发一种只允许你构建有效证明的语言。 ML，代表“元语言”，是这项工作的结果。 ML 的类型系统经过精心构建，因此您只能在该语言中构建有效的证明。然后将定理证明器编写为构建证明的程序。最终，这门“经典元语言”演变成了一种成熟的编程语言。

在 80 年代初期，ML 社区出现了分裂，一方面是法国人，另一方面是英国和美国。法国人继续开发 CAML，后来开发了Objective CAML (OCaml)，而英国人和美国人开发了Standard ML语言。这两种方言非常相似。微软在 2005 年推出了自己的 OCaml 变体，称为 F#。

米尔纳在 1991 年获得了图灵奖，这在很大程度上是因为他在ML方面的工作。 ACM网站为他的颁奖词中写到：

NOTE: ML语言遥遥领先于那个时代。它建立在简洁明了的数学思想之上，经过梳理，可以独立研究，并且相对容易地重新混合和重复使用。 ML 影响了许多实用语言，包括 Java、Scala 和 Microsoft 的 F#。事实上，任何认真的语言设计师都不应该忽视这个优秀设计的例子。

==== 工业界

OCaml和其他函数式语言远不及C、C++和Java流行。OCaml的真正优势在于编程语言方面的应用（即编译器、分析器、验证器、证明器等）。这并不奇怪，因为OCaml是从定理证明领域演变而来的。

这并不是说函数式语言不在工业中使用。有许多行业项目使用OCaml和Haskell以及其他语言。康奈尔大学的Yaron Minsky (PhD '02)写了一篇关于在金融行业使用OCaml的论文（必须从康奈尔大学的网络内部访问该链接）。它解释了OCaml的特性如何使其成为快速构建可运行的复杂软件的理想选择。

但最终这门课程是关于你作为程序员的教育，而不是关于给你找工作。

NOTE: “教育就是忘记在学校学到的一切之后剩下的东西。” —— 爱因斯坦

OCaml在阐明和简化函数式编程的本质方面做得很好，这是其他融合函数式和命令式编程（如Scala）或将函数式编程发挥到极致（如Haskell）的语言所没有的。学习了OCaml后，您将有能力自学任何其他函数式（受启发）语言。

==== 美丽的OCaml

一个非科学的、主观的研究OCaml的理由，我将作为我自己的观点提出：OCaml很漂亮。

NOTE: “美丽是我们的事业” —— 来自纪念Edsger W. Dijkstra的一本书的书名

（Dijkstra于1972年因“对编程的基本贡献”而获得图灵奖。David Gries是该书的编辑。）

OCaml优雅、简单、美丽。您编写的代码可以时尚而有品位。起初，这可能并不明显。毕竟，您正在学习一门新语言——您不会期望在SANSK 1131课程的第一天欣赏梵文诗歌。事实上，当您努力用新语言表达自己时，您可能会感到沮丧一段时间。所以给它一些时间。我已经记不清有多少学生在未来的学期回来告诉我，在3110之后他们重新使用其他语言写作后感觉有多“丑陋”。

审美很重要。代码不仅仅是为了让机器执行而编写的。它也是为了与人类交流而编写的。优雅的代码更易于阅读和维护。当然，写起来不一定更容易。

=== 可变性

命令式编程语言（例如C和Java）涉及在整个执行过程中都会发生变化的可变状态。命令通过破坏性地改变该状态来指定如何计算。除了产生返回值之外，过程（或方法）可能具有更新状态的副作用。

*可变性的幻想* 让我们觉得程序很容易推理：机器先做这个，然后做这个，等等。

*可变性的现实* 是，虽然机器擅长复杂的状态操作，但人类不擅长理解它。之所以如此，其本质是可变性破坏了引用透明性：在不影响计算结果的情况下用其值替换表达式的能力。在数学中，如果 stem:[f(x)=y] ，那么您可以在任何看到 stem:[f(x)] 的地方替换成 stem:[y] 。在命令式语言中，就不能这样了： stem:[f] 可能有副作用，因此在时间 stem:[t] 计算 stem:[f(x)] 可能会导致与时间 stem:[t'] 不同的值。

人们很容易相信机器可以操纵一种状态，并且机器一次只做一件事。计算机系统不遗余力地试图提供这种错觉。但这只是：一种错觉。实际上，有许多状态分布在线程、内核、处理器和联网计算机上。机器同时做很多事情。可变性使得关于分布式状态和并发执行的推理变得非常困难。

然而， *不可变性* 将程序员从这些担忧中解放出来。它提供了构建正确和并发程序的强大方法。OCaml主要是一种不可变语言，就像大多数函数式语言一样。它确实支持具有可变状态的命令式编程，但是我们在课程开始大约两个月后才会使用这些功能——部分原因是因为我们根本不需要它们，部分原因是为了让你从“过程式编程”中退出来，否则无法摆脱对可变性的依赖。这种不受可变性影响的自由是3110课程可以为您带来的最大视角变化之一。

=== 总结

本课程是关于成为一名更好的程序员。学习函数式编程将对此有所帮助。我们遇到的最大障碍是说一种新语言时的挫败感，尤其是放弃可变状态。但好处将是巨大的：发现编程超越了任何特定语言或语言家族的编程，接触到高级语言功能，以及对美的欣赏。

==== 术语和概念

* dynamic typing：动态类型
* first-class functions：函数作为一等公民
* functional programming languages：函数式编程语言
* immutability：不可变性
* Lisp
* ML
* OCaml
* referential transparency：引用透明
* side effects：副作用
* state：状态
* static typing：静态类型
* type safety：类型安全

== OCaml基础

本章将介绍OCaml的一些基本特性。但在我们深入学习OCaml之前，让我们先谈谈一个更大的想法：学习一般的语言。

本课程的次要目标之一不仅仅是让您学习一门新的编程语言，而是提高您学习新语言的技能。

学习一门语言有五个基本要素：语法、语义、习语、库和工具。

*语法*

通过语法，我们指的是定义语言中文本格式良好程序的规则，包括关键字、对空格和格式的限制、标点符号、运算符等。学习新语言的一个更令人讨厌的方面可能是与您已经知道的语言相比，语法感觉很奇怪。但是你学习的语言越多，你就越习惯于接受语言的语法，而不是希望它有所不同。（如果你想看到一些语法非常不寻常的语言，看看APL，它需要自己的扩展键盘，以及Whitespace，其中程序完全由空格、制表符和换行符组成。）你需要了解语法只是为了完全可以对着电脑说话。

*语义*

通过语义，我们指的是定义程序行为的规则。换句话说，语义是关于程序的意义——特定句法代表什么计算。请注意，尽管“语义”是复数形式，但我们将其用作单数。这类似于“数学”或“物理学”。

语义有两个部分，语言的动态语义和语言的静态语义。动态语义定义程序在执行或评估时的运行时行为。静态语义定义了编译时检查，以确保程序合法，超出任何语法要求。最重要的静态语义可能是类型检查：定义程序类型是否正确的规则。学习一门新语言的语义通常是真正的挑战，即使语法可能是你必须克服的第一个障碍。您需要了解语义才能说出您对计算机的意义，并且您需要说出您的意思，以便您的程序执行正确的计算。

*习语*

习语是指使用语言特征来表达计算的常用方法。鉴于您可以在一种语言中以多种方式表达一种计算，您会选择哪一种？有些会比其他的更自然。精通该语言的程序员会更喜欢某些表达方式。我们可以从有效使用语言中的主导范式的角度来考虑这一点，无论它们是命令式的、函数式的、面向对象的，等等。您需要理解习语来表达您的意思，不仅对计算机，而且对其他程序员。当您按习惯编写代码时，其他程序员会更好地理解您的代码。

*库*

库是已经为您编写的代码包，可以使您成为更有效率的程序员，因为您不必自己编写代码。 （据说懒惰是程序员的美德。）学习一门新语言的一部分是发现哪些库可用以及如何使用它们。一种语言通常提供一个标准库，让您可以访问一组核心功能，其中大部分功能您自己无法用该语言编写，例如文件I/O。

*工具*

至少任何语言实现都提供编译器或解释器作为与使用该语言的计算机进行交互的工具。但是还有其他种类的工具：调试器；集成开发环境（IDE）；以及性能、内存使用和正确性等方面的分析工具。学习使用与语言相关的工具也可以让你成为一个更有效率的程序员。有时很容易将工具本身与语言混淆；例如，如果您只将 Eclipse 和 Java 一起使用过，那么 Eclipse 是一个适用于多种语言的 IDE，并且可以在没有 Eclipse 的情况下使用 Java，这可能并不明显。

在本课中学习 OCaml 时，我们的重点主要是语义和习语。当然，我们必须一路学习语法，但这不是我们学习的有趣部分。我们将接触 OCaml 标准库和其他几个库，特别是 OUnit（一个类似于 JUnit、HUnit 等的单元测试框架）。除了 OCaml 编译器和构建系统之外，我们将使用的主要工具是 toplevel，它提供了对代码进行交互试验的能力。

=== 和OCaml进行交互


`toplevel` 就像一个计算器或OCaml的命令行界面。它类似于DrJava，如果您在CS 2110中使用它，或者类似于交互式Python解释器，如果您在CS 1110中使用它。它对于尝试小段代码非常方便，而无需费心启动OCaml编译器。但是不要太依赖它，因为创建、编译和测试大型程序将需要更强大的工具。其他一些语言将 `toplevel` 称为REPL，它代表 `read-eval-print-loop` ：它读取程序员输入，然后求值，打印结果，然后循环。

在终端窗口中，键入 `utop` 以启动顶层。按 `Control-D` 退出 `utop` 。你也可以输入 `#quit;;` 并按回车。请注意，您必须在那里键入 `#` ：它是您已经看到的 `#` 提示的补充。

==== 类型和值

您可以在OCaml `utop` 中输入表达式。以双分号 `;;` 结束表达式然后按回车键。 OCaml然后将对表达式求值，告诉您结果值和值的类型。例如：

[source,text]
----
# 42;;
- : int = 42
----

让我们从 `utop` 中分析该响应，从右到左阅读：

* `42` 是一个值
* `int` 是值的类型
* 我们并没有给值命名，所以它的名字是符号 `-`

我们可以使用 `let` 定义来将值绑定到名字，例如：

[source,text]
----
# let x = 42;;
val x : int = 42
----

让我们从 `utop` 中分析该响应，从左到右阅读：

* 一个值绑定到了一个名字，所以是 `val` 关键字
* `x` 是值绑定到的名字
* `int` 是值的类型
* `42` 是值

你可以说“ `x` 的类型是 `int` ， 等于 `42` 。”

==== 函数

在 `utop` 中，函数定义语法如下：

[source,text]
----
# let increment x = x+1;;
val increment : int -> int = <fun>
----

分析一下响应：

* `increment` 是值绑定到的标识符。
* `int -> int` 是值的类型。这是一种将 `int` 作为输入并生成 `int` 作为输出的函数。将箭头 `->`` 视为一种将一个值转换为另一个值的视觉隐喻——这就是函数所做的。
* 该值是一个函数， `utop` 选择不打印它（因为它现在已经被编译并且在内存中具有不容易进行漂亮打印的表示）。相反， `utop` 打印 `<fun>` ，它只是一个占位符，表明存在一些不可打印的函数值。重要提示： `<fun>` 本身不是一个值。

我们可以用如下语法来调用函数：

[source,text]
----
# increment 0;;
- : int = 1
# increment(21);;
- : int = 22
# increment (increment 5);;
- : int = 7
----

但是在OCaml中，通常的词汇是我们“应用(apply)”函数而不是“调用(call)”它。

请注意OCaml在是否写括号以及是否写空格方面是如何具有灵活性的。第一次学习OCaml的挑战之一是弄清楚何时真正需要括号。因此，如果您发现自己遇到语法错误的问题，一种策略是尝试添加一些括号。

==== 将代码储存在文件中

使用OCaml作为一种交互式计算器可能很有趣，但我们不会用这种方式编写大型程序。我们需要将代码存储在文件中。

打开终端并使用文本编辑器创建一个名为 `hello.ml` 的文件。在文件中输入以下代码：

[source,ocaml]
----
let _ = print_endline "Hello world!"
----

NOTE: 没有双分号 `;;` 在该行代码的末尾。双分号严格用于 `utop` 中的交互式会话，以便 `utop` 知道您已完成输入一段代码。没有理由将它写在 `.ml` 文件中，我们认为这样做有点糟糕。

上面的 `let _ =` 意味着我们不关心在 `=` 的右侧代码的命名（因此是“空白”或下划线）。

保存文件并返回到命令行。编译代码：

[source,bash]
----
$ ocamlc -o hello.byte hello.ml
----

编译器名为 `ocamlc` 。 `-o hello.byte` 选项表示将输出可执行文件命名为 `hello.byte` 。可执行文件包含已编译的OCaml字节码。此外，还生成了另外两个文件， `hello.cmi` 和 `hello.cmo` 。我们现在不需要关心这些文件。运行可执行文件：

[source,bash]
----
$ ./hello.byte
----

它应该打印 `Hello world!` 并终止。

现在将打印的字符串更改为您选择的内容。保存文件，重新编译并重新运行。尝试使代码打印多行。

如果您习惯于在 Eclipse 等 IDE 中工作，那么编辑器和命令行之间的这种编辑-编译-运行循环可能会感到陌生。别担心；它很快就会成为第二天性。

直接运行编译器很好知道怎么做，但是在较大的项目中，我们希望使用 OCaml 构建系统来自动查找和链接库。让我们尝试使用它：

[source,bash]
----
$ ocamlbuild hello.byte
----

您将从该命令中收到错误消息。别担心；继续阅读这个练习。

构建系统名为 `ocamlbuild` 。我们要求它构建的文件是编译后的字节码 `hello.byte` 。构建系统将自动确定 `hello.ml` 是所需字节码的源代码。

然而，构建系统喜欢负责整个编译过程。当它看到直接调用编译器生成的剩余文件时，就像我们在前面的练习中所做的那样，它理所当然地感到紧张并拒绝继续。如果您查看错误消息，它表示已生成脚本以清除旧编译。运行该脚本，并删除编译后的文件：

[source,bash]
----
$ _build/sanitize.sh
$ rm hello.byte
----

然后重新构建：

[source,bash]
----
$ ocamlbuild hello.byte
----

现在应该成功了。将创建一个目录 `_build` ；它包含所有已编译的代码。这是构建系统相对于直接运行编译器的一个好处：不是用一堆生成的文件污染源目录，而是在单独的目录中干净地创建它们。还有一个文件 `hello.byte` 被创建，它实际上只是一个指向该名称的“真实”文件的链接，该文件位于 `_build` 目录中。

现在运行可执行文件：

[source,bash]
----
$ ./hello.byte
----

我们可以很容易的清理掉所有编译过的代码：

[source,bash]
----
$ ocamlbuild -clean
----

然后就会删除掉 `_build` 目录以及 `hello.byte` 链接，只剩下我们写的源代码。

==== Main函数呢？

与 C 或 Java 不同，OCaml 程序不需要有一个名为 main 的特殊函数来启动程序。通常的习惯用法是将文件中的最后一个定义作为主函数，启动要完成的任何计算。

==== 在 `utop` 中载入代码

除了允许您定义函数之外， `utop` 还将接受不是 OCaml 代码的指令，而是告诉 `utop` 本身做某事。所有指令都以 `#` 字符开头。也许最常见的指令是 `#use` ，它将文件中的所有代码加载到 `utop` ，就像您已将该文件中的代码输入到 `utop` 一样。

例如，假设您创建了一个名为 `mycode.ml` 的文件。

在该文件中放入以下代码：

[source,ocaml]
----
let inc x = x + 1
----

启动 `utop` 。尝试输入以下表达式，并观察错误：

[source,text]
----
# inc 3;;
Error: Unbound value inc
Hint: Did you mean incr?
----

发生错误是因为 `utop` 还不知道有关名为 `inc` 的函数的任何信息。现在向 `utop` 发出以下指令：

[source,text]
----
# #use "mycode.ml";;
----

请注意，上面的第一个 `#` 字符表示对 `utop` 的提示符。第二个 `#` 字符是您键入的字符，用于告诉 `utop` 您正在发出指令。如果没有该字符， `utop` 会认为您正在尝试应用名为 `use` 的函数。

现在再试一次：

[source,text]
----
# inc 3;;
- : int = 4
----

==== `utop` 工作流

将 `utop` 与存储在文件中的代码一起使用时的最佳工作流程是：

* 在文件中编辑代码
* 使用 `#use` 将代码加载到 `utop`
* 测试代码
* 退出 `utop` 。注意：不要忽略这一步

假设您想修复代码中的错误：很可能不退出 `utop` ，编辑文件，然后将 `#use` 指令重新发出到同一个 `utop` 会话中。抵制这种诱惑。从同一会话中较早的 `#use` 指令加载的“陈旧代码”可能会导致令人惊讶的事情发生——无论如何，当您第一次学习该语言时，会感到惊讶。 *所以在重新使用文件之前总是退出顶层。*