= OCaml函数式编程
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectnums:

== 简介

=== 编程语言

一个伟大的通用编程语言：

* 让我们写的代码很简洁，容易理解，并位于正确的抽象层级
* 让我们为语言扩展新特性时，可以很好的融入语言的其他特性中
* 容易写出正确的代码，且性能很好
* 容易重构代码
* 容易重用代码
* 容易学习

可能有数千种通用语言。但是没有普遍优秀的编程语言。

通用语言来来去去。在您的生活中，您可能会学到一些东西。今天，它是 Java 和 C++。昨天是 Pascal 和 C。在此之前，是 Fortran 和 Lisp。谁知道明天会怎样？您可能会为特定项目使用数十种专用语言。在这个快速变化的领域，您需要能够快速适应。

*一个好的程序员必须学习如何学习新语言。*

我们使用无数种不同的编程语言来与机器和彼此进行通信：

* 通用编程语言和脚本语言: Fortran, Lisp, Basic, C, Pascal, Scheme, C++, Java, C#, Visual Basic, Perl, Python, Ruby, PHP, Javascript, Clojure, Scala, Erlang, Swift, ...
* 工具类语言: awk, sed, tcl, sh, csh, bash, ...
* 搜索类语言: regular expressions, browser queries, SQL, ...
* 展示和渲染类语言: PostScript, PDF, HTML, XML, ...
* 硬件编程语言: CCS, VHDL, Verilog, ...
* 定理证明和数学语言: Mathematica, Maple, Matlab, R, NuPRL, Isabelle/HOL, ACL2, Coq

了解超越任何特定语言细节的编程背后的原则至关重要。没有比从完全不同的角度处理编程更好的方法来了解这些原则。

=== OCaml

我们通过学习 OCaml 开始这门课程正是出于这个原因：它与你们大多数人在以前的编程课程中看到的观点截然不同。由于您已经学习了 1110 和 2110，您已经学会了如何编程。本课程让您有机会从头开始学习一门新语言，并在此过程中反思编程与语言编程之间的区别。

>“一种不会影响你对编程的思考方式的语言是不值得了解的。” ———— Alan J. Perlis (1922-1990)，图灵奖首位获得者

*OCaml将改变您对编程的看法。*

OCaml 是一种函数式编程语言。函数式语言的关键语言抽象是数学函数。函数将输入映射到输出；对于相同的输入，它总是产生相同的输出。也就是说，数学函数是无状态的：它们不维护任何在函数使用之间持续存在的额外信息或状态。函数是一等公民：您可以将它们用作其他函数的输入，并生成函数作为输出。用函数来表达一切可以实现一个统一而简单的编程模型，它比其他语言家族中的过程和方法更容易推理。

OCaml 支持许多高级功能，其中一些您以前会遇到过，而其中一些可能是新的：


* 代数数据类型：您可以轻松地在 OCaml 中构建复杂的数据结构，而无需担心指针和内存管理。模式匹配使它们更加方便。
* 类型推断：您不必到处写下类型信息。编译器会自动计算出大多数类型。这可以使代码更易于阅读和维护。
* 参数多态：函数和数据结构可以在类型上参数化。这对于能够重用代码至关重要。
* 垃圾收集：自动内存管理使您免于内存分配和释放的负担，这是 C 等语言中错误的常见来源。
* 模块：OCaml 通过使用模块可以轻松构建大型系统。模块（称为结构）用于封装接口（称为签名）背后的实现。通过提供操作模块的函数（称为函子），OCaml 远远超出了大多数带有模块的语言的功能。

OCaml 是一种静态类型和类型安全的编程语言。静态类型语言在编译时检测类型错误，因此无法执行带有类型错误的程序。类型安全语言限制了可以对哪些类型的数据执行哪些类型的操作。在实践中，这可以防止许多愚蠢的错误（例如，将整数视为函数）并防止许多安全问题：计算机紧急响应小组（CERT，美国政府机构，负责网络安全）报告的入侵事件中超过一半是由于缓冲区溢出，这在类型安全的语言中是不可能的。

一些语言，如 Scheme 和 Lisp，是类型安全的，但是是动态类型的。也就是说，类型错误仅在运行时被捕获。其他语言，如 C 和 C++，是静态类型的，但不是类型安全的。不能保证不会发生类型错误。

从谱系上讲，OCaml 来自其祖父是 Lisp 的编程语言系列，其中包括 Clojure、F#、Haskell 和 Racket 等现代语言。函数式语言有一种令人惊讶的趋势来预测更多主流语言的未来。 Java 于 1995 年将垃圾收集带入主流； Lisp 在 1958 年就有了它。Java 直到 2004 年的第 5 版才有泛型； ML 系列在 1990 年就有了它。在过去的 10 年里，一流的函数和类型推断已经被纳入主流语言，如 Java、C# 和 C++，在函数式语言引入它们很久之后。通过学习函数式编程，您可以了解接下来可能会发生什么。谁知道它可能是什么？ （我打赌是模式匹配。）

==== OCaml的历史

70 年代末和 80 年代初，苏格兰爱丁堡计算机科学实验室的 Robin Milner 和其他人正在研究定理证明器。传统上，定理证明器是用 Lisp 等语言实现的。米尔纳不断遇到这样一个问题，即定理证明器有时会将不正确的“证明”（即错误证明）放在一起并声称它们是有效的。所以他试图开发一种只允许你构建有效证明的语言。 ML，代表“元语言”，是这项工作的结果。 ML 的类型系统经过精心构建，因此您只能在该语言中构建有效的证明。然后将定理证明器编写为构建证明的程序。最终，这门“经典元语言”演变成了一种成熟的编程语言。

在 80 年代初期，ML 社区出现了分裂，一方面是法国人，另一方面是英国和美国。法国人继续开发 CAML，后来开发了Objective CAML (OCaml)，而英国人和美国人开发了Standard ML语言。这两种方言非常相似。微软在 2005 年推出了自己的 OCaml 变体，称为 F#。

米尔纳在 1991 年获得了图灵奖，这在很大程度上是因为他在ML方面的工作。 ACM网站为他的颁奖词中写到：

>ML语言遥遥领先于那个时代。它建立在简洁明了的数学思想之上，经过梳理，可以独立研究，并且相对容易地重新混合和重复使用。 ML 影响了许多实用语言，包括 Java、Scala 和 Microsoft 的 F#。事实上，任何认真的语言设计师都不应该忽视这个优秀设计的例子。

==== 工业界


OCaml和其他函数式语言远不及C、C++和Java流行。OCaml的真正优势在于编程语言方面的应用（即编译器、分析器、验证器、证明器等）。这并不奇怪，因为OCaml是从定理证明领域演变而来的。

这并不是说函数式语言不在工业中使用。有许多行业项目使用OCaml和Haskell以及其他语言。康奈尔大学的Yaron Minsky (PhD '02)写了一篇关于在金融行业使用OCaml的论文（必须从康奈尔大学的网络内部访问该链接）。它解释了OCaml的特性如何使其成为快速构建可运行的复杂软件的理想选择。

但最终这门课程是关于你作为程序员的教育，而不是关于给你找工作。

>“教育就是忘记在学校学到的一切之后剩下的东西。” ———— 爱因斯坦

OCaml在阐明和简化函数式编程的本质方面做得很好，这是其他融合函数式和命令式编程（如Scala）或将函数式编程发挥到极致（如Haskell）的语言所没有的。学习了OCaml后，您将有能力自学任何其他函数式（受启发）语言。

==== 美丽的OCaml

一个非科学的、主观的研究OCaml的理由，我将作为我自己的观点提出：OCaml很漂亮。

>“美丽是我们的事业” ———— 来自纪念Edsger W. Dijkstra的一本书的书名

（Dijkstra于1972年因“对编程的基本贡献”而获得图灵奖。David Gries是该书的编辑。）

OCaml优雅、简单、美丽。您编写的代码可以时尚而有品位。起初，这可能并不明显。毕竟，您正在学习一门新语言——您不会期望在SANSK 1131课程的第一天欣赏梵文诗歌。事实上，当您努力用新语言表达自己时，您可能会感到沮丧一段时间。所以给它一些时间。我已经记不清有多少学生在未来的学期回来告诉我，在3110之后他们重新使用其他语言写作后感觉有多“丑陋”。

审美很重要。代码不仅仅是为了让机器执行而编写的。它也是为了与人类交流而编写的。优雅的代码更易于阅读和维护。当然，写起来不一定更容易。

